function OUT = fun_importfile_EJ2022_cvs(filename, dataLines)
%IMPORTFILE Import data from a text file
%  OUT = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  OUT = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  OUT = importfile("/home/juank/Desktop/EJN2022/data/output/EJN2022_16subj_GeneralFilters.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Nov-2022 18:18:05

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 27);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["refix", "pretarget", "multifix", "urevent", "tonset", "dur_added", "rank", "first_rank", "stposrel", "stposabs", "n", "x", "y", "istarget", "isdistractor", "distractor_cat", "ditractor_atr", "trial_targetseen", "trial_correct", "trial_cat", "trial_resp", "trial_atr", "trial_type", "trial_cattype", "trial_number", "trial_subject", "trial_bgn_latency"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "categorical", "double", "double", "categorical", "categorical", "categorical", "categorical", "categorical", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["distractor_cat", "ditractor_atr", "trial_cat", "trial_resp", "trial_atr", "trial_type", "trial_cattype"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "trial_subject", "TrimNonNumeric", true);
opts = setvaropts(opts, "trial_subject", "ThousandsSeparator", ",");

% Import the data
OUT = readtable(filename, opts);

end